apiVersion: v1
kind: Pod
metadata:
  name: nr-test
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}
  initContainers:
  - name: nr-apm-initcontainers
    image: luckypenny79/nr-java-apm:1.4
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /opt
      name: shared-volume
  containers:
  - name: nr-test
    image: luckypenny79/ubuntu:1.0 
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /newrelic
      name: shared-volume
      readOnly: true
