apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
  - path: patch.yaml
    target:
      kind: Deployment
  - path: datadog-apm.yaml
    target:
      kind: Deployment
images:
- name: app
  newName: docker.pkg.github.com/luckypenny/apps/api-app1
  newTag: GIT-0540f3c
